spring.datasource.url=${SPRING_DATASOURCE_URL:\
jdbc:mysql://localhost:3306/books?\
allowPublicKeyRetrieval=true&\
useSSL=false&\
serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.expiration=3000000
jwt.secret=askjdhdjsjhdsjka437398odklkllllbvjkbvmjdhksjksj
